# Generated by Django 3.0.5 on 2021-05-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20210514_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, upload_to='photos/category/%Y/%m/%d/', verbose_name='تصویر دسته بندی'),
        ),
    ]
