# Generated by Django 3.0.5 on 2021-05-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_category_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_in_homepage',
            field=models.BooleanField(default=False, verbose_name='نمایش در لندینگ'),
        ),
    ]
