# Generated by Django 3.0.5 on 2021-05-17 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_fname', models.CharField(max_length=255, verbose_name='نام مشتری')),
                ('customer_lname', models.CharField(max_length=255, verbose_name='نام خانوادگی مشتری')),
                ('customer_phone', models.CharField(max_length=255, verbose_name='شماره تماس')),
                ('customer_province', models.CharField(max_length=255, verbose_name='استان')),
                ('customer_city', models.CharField(max_length=255, verbose_name='شهر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش ها',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.Order')),
            ],
        ),
    ]
