# Generated by Django 3.0.5 on 2021-06-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20210614_0931'),
        ('cart', '0002_orderproduct_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_order',
            field=models.ManyToManyField(null=True, related_name='rel_orders', to='products.Product'),
        ),
    ]
