# Generated by Django 3.0.5 on 2021-06-15 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order_customer_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_order',
        ),
    ]
