# Generated by Django 3.0.5 on 2021-05-14 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_auto_20210514_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='نام محصول')),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('product_photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='تصویر محصول')),
                ('type', models.CharField(choices=[('Stock', 'Stock'), ('Original', 'Original')], default='Original', max_length=8)),
                ('tech_spec', models.FileField(blank=True, upload_to='spec/%Y/%m/%d/', verbose_name='مشخصات محصول')),
                ('show_in_homepage', models.BooleanField(default=False, verbose_name='نمایش در لندینگ')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categories.Category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
    ]
