# Generated by Django 3.0.5 on 2021-05-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AddField(
            model_name='product',
            name='alternative_name_1',
            field=models.CharField(blank=True, max_length=255, verbose_name='نام های دیگر'),
        ),
        migrations.AddField(
            model_name='product',
            name='alternative_name_2',
            field=models.CharField(blank=True, max_length=255, verbose_name='نام های دیگر'),
        ),
        migrations.AddField(
            model_name='product',
            name='alternative_name_3',
            field=models.CharField(blank=True, max_length=255, verbose_name='نام های دیگر'),
        ),
        migrations.AddField(
            model_name='product',
            name='alternative_name_4',
            field=models.CharField(blank=True, max_length=255, verbose_name='نام های دیگر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Stock', 'Stock'), ('Original', 'Original')], default='Original', max_length=8, verbose_name='وضعیت'),
        ),
    ]
