# Generated by Django 3.0.5 on 2021-05-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210514_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_photo',
            field=models.ImageField(blank=True, upload_to='photos/product/%Y/%m/%d/', verbose_name='تصویر محصول'),
        ),
    ]
