# Generated by Django 3.0.5 on 2021-06-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210521_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reviews_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
