# Generated by Django 3.0.5 on 2021-06-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_reviews_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reviews_count',
            field=models.IntegerField(default=0, editable=False, null=True),
        ),
    ]
